/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package visualaveraginglibrary;

import averagingAlgorithms.averagingMethods;
import javax.swing.SpinnerNumberModel;

public class parametersWindow extends javax.swing.JDialog {

    /**
     * Creates new form parametersWindow
     */
    public parametersWindow(VAveLib_GUI mainWin) {
        initComponents();
        critChiConfSpinner.setModel(new SpinnerNumberModel(mainWin.paramArray[0], 10d, 100d, 0.5d));
        LWMmaxweightSpinner.setModel(new SpinnerNumberModel(mainWin.paramArray[1], 50d, 100d, 5d));
        LWMoutlierMethodComboBox.setSelectedIndex((int) mainWin.paramArray[2]);
        NRMoutlierConfSpinner.setModel(new SpinnerNumberModel(mainWin.paramArray[3], 10d, 100d, 0.5d));
        RTconfComboBox.setSelectedIndex((int) mainWin.paramArray[4]);
        bootstrapMedianSpinner.setModel(new SpinnerNumberModel(mainWin.paramArray[5], 500000, 1000000, 100));
        mpNumericSpinner.setModel(new SpinnerNumberModel(mainWin.paramArray[6], 0.001d, 0.1d, 0.001d));
        mpItSpinner.setModel(new SpinnerNumberModel(mainWin.paramArray[7], 500, 5000, 50));
        mainWindow = mainWin;
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        critChiConfSpinner = new javax.swing.JSpinner();
        jLabel11 = new javax.swing.JLabel();
        LWMmaxweightSpinner = new javax.swing.JSpinner();
        jLabel12 = new javax.swing.JLabel();
        LWMoutlierMethodComboBox = new javax.swing.JComboBox();
        NRMoutlierConfSpinner = new javax.swing.JSpinner();
        jLabel13 = new javax.swing.JLabel();
        RTconfComboBox = new javax.swing.JComboBox();
        bootstrapMedianSpinner = new javax.swing.JSpinner();
        jLabel14 = new javax.swing.JLabel();
        mpNumericSpinner = new javax.swing.JSpinner();
        mpItSpinner = new javax.swing.JSpinner();
        defaultButton = new javax.swing.JButton();
        paramOKbutton = new javax.swing.JButton();
        paramCancelButton = new javax.swing.JButton();

        jLabel1.setText("Critical Chi**2 Confidence Level:");

        jLabel2.setText("Parameters used in averaging procedures:");

        jLabel3.setText("<html>Limitation of Statistical Weights; maximum weight:<br>\n(Recommended to be 50% by the IAEA)</html>");

        jLabel4.setText("Limitation of Statistical Weights; outlier criterion");

        jLabel5.setText("<html>Normalized Residuals Methods; outlier confidence level:<br> (Outliers will have their uncertainties uncreased)</html>");

        jLabel6.setText("<html>Rajeval Technique; outlier confidence level:<br>\n(User will be asked to remove outliers from the dataset)</html>");

        jLabel7.setText("Bootstrap; number of sub-sample medians to take:");

        jLabel9.setText("Mandel-Paule; numeric tolarance:");

        jLabel10.setText("Mandel-Paule; maximum number of iterations:");

        critChiConfSpinner.setMinimumSize(new java.awt.Dimension(60, 25));
        critChiConfSpinner.setPreferredSize(new java.awt.Dimension(60, 25));
        critChiConfSpinner.addChangeListener(new javax.swing.event.ChangeListener() {
            public void stateChanged(javax.swing.event.ChangeEvent evt) {
                critChiConfSpinnerStateChanged(evt);
            }
        });

        jLabel11.setText("(%)");

        jLabel12.setText("(%)");

        LWMoutlierMethodComboBox.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Chauvenet", "Peirce", "Modified Peirce", "Birch" }));

        NRMoutlierConfSpinner.addChangeListener(new javax.swing.event.ChangeListener() {
            public void stateChanged(javax.swing.event.ChangeEvent evt) {
                NRMoutlierConfSpinnerStateChanged(evt);
            }
        });

        jLabel13.setText("(%)");

        RTconfComboBox.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "95%", "99%", "99.99%" }));
        RTconfComboBox.setSelectedIndex(1);

        jLabel14.setText("x10^(-10)");

        defaultButton.setText("Restore Default Values");
        defaultButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                defaultButtonActionPerformed(evt);
            }
        });

        paramOKbutton.setText("OK");
        paramOKbutton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                paramOKbuttonActionPerformed(evt);
            }
        });

        paramCancelButton.setText("Cancel");
        paramCancelButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                paramCancelButtonActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jLabel1)
                                .addGap(82, 82, 82))
                            .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(142, 142, 142)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(NRMoutlierConfSpinner)
                                .addGap(18, 18, 18)
                                .addComponent(jLabel13))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(critChiConfSpinner, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addGap(18, 18, 18)
                                .addComponent(jLabel11))
                            .addComponent(LWMoutlierMethodComboBox, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(LWMmaxweightSpinner)
                                .addGap(18, 18, 18)
                                .addComponent(jLabel12)))
                        .addGap(33, 33, 33))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel6, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel5, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel7))
                        .addGap(84, 84, 84)
                        .addComponent(bootstrapMedianSpinner)
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel2)
                            .addComponent(jLabel4)
                            .addComponent(jLabel10))
                        .addGap(95, 95, 95)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(mpItSpinner)
                            .addComponent(mpNumericSpinner))
                        .addGap(18, 18, 18)
                        .addComponent(jLabel14)
                        .addGap(33, 33, 33))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addComponent(RTconfComboBox, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(70, 70, 70))))
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jLabel9))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(180, 180, 180)
                        .addComponent(defaultButton)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(54, 54, 54)
                .addComponent(paramOKbutton)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(paramCancelButton)
                .addGap(85, 85, 85))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel2)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(jLabel1)
                                    .addComponent(critChiConfSpinner, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jLabel11))
                                .addGap(18, 18, 18)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                        .addComponent(LWMmaxweightSpinner, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addComponent(jLabel12)))
                                .addGap(18, 18, 18)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(jLabel4)
                                    .addComponent(LWMoutlierMethodComboBox, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(18, 18, 18)
                                .addComponent(jLabel5, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                .addComponent(NRMoutlierConfSpinner, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(jLabel13)))
                        .addGap(18, 18, 18)
                        .addComponent(jLabel6, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(RTconfComboBox, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel7)
                    .addComponent(bootstrapMedianSpinner, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel9)
                    .addComponent(mpNumericSpinner, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel14))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(mpItSpinner, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel10))
                .addGap(18, 18, 18)
                .addComponent(defaultButton)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(paramCancelButton)
                    .addComponent(paramOKbutton))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void defaultButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_defaultButtonActionPerformed
        setDefaultValues();
    }//GEN-LAST:event_defaultButtonActionPerformed

    private void paramOKbuttonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_paramOKbuttonActionPerformed
        mainWindow.paramArray[0] = (double) critChiConfSpinner.getValue();
        averagingMethods.critChiSqConf = (double) critChiConfSpinner.getValue()/100d;
        mainWindow.paramArray[1] = (double) LWMmaxweightSpinner.getValue();
        mainWindow.paramArray[2] = (double) LWMoutlierMethodComboBox.getSelectedIndex();
        mainWindow.paramArray[3] = (double) NRMoutlierConfSpinner.getValue();
        mainWindow.paramArray[4] = (double) RTconfComboBox.getSelectedIndex();
        mainWindow.paramArray[5] = Double.parseDouble(bootstrapMedianSpinner.getValue().toString()); //Note: java has trouble converting integers to strings...
        mainWindow.paramArray[6] = (double) mpNumericSpinner.getValue();
        mainWindow.paramArray[7] = Double.parseDouble(mpItSpinner.getValue().toString());
        
        this.dispose();
    }//GEN-LAST:event_paramOKbuttonActionPerformed

    private void paramCancelButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_paramCancelButtonActionPerformed
        this.dispose();
    }//GEN-LAST:event_paramCancelButtonActionPerformed

    private void critChiConfSpinnerStateChanged(javax.swing.event.ChangeEvent evt) {//GEN-FIRST:event_critChiConfSpinnerStateChanged
        if((double) critChiConfSpinner.getValue() > 99.99d){
            critChiConfSpinner.setValue(99.99d);
        }
    }//GEN-LAST:event_critChiConfSpinnerStateChanged

    private void NRMoutlierConfSpinnerStateChanged(javax.swing.event.ChangeEvent evt) {//GEN-FIRST:event_NRMoutlierConfSpinnerStateChanged
        if((double) NRMoutlierConfSpinner.getValue() > 99.99d){
            NRMoutlierConfSpinner.setValue(99.99d);
        }
    }//GEN-LAST:event_NRMoutlierConfSpinnerStateChanged

    
    public void setDefaultValues(){
        
        critChiConfSpinner.setValue(95d);
        LWMmaxweightSpinner.setValue(50d);
        LWMoutlierMethodComboBox.setSelectedIndex(0);
        NRMoutlierConfSpinner.setValue(99d);
        RTconfComboBox.setSelectedIndex(1);
        bootstrapMedianSpinner.setValue(800000);
        mpNumericSpinner.setValue(0.010d);
        mpItSpinner.setValue(1000);
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JSpinner LWMmaxweightSpinner;
    private javax.swing.JComboBox LWMoutlierMethodComboBox;
    private javax.swing.JSpinner NRMoutlierConfSpinner;
    private javax.swing.JComboBox RTconfComboBox;
    private javax.swing.JSpinner bootstrapMedianSpinner;
    private javax.swing.JSpinner critChiConfSpinner;
    private javax.swing.JButton defaultButton;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JSpinner mpItSpinner;
    private javax.swing.JSpinner mpNumericSpinner;
    private javax.swing.JButton paramCancelButton;
    private javax.swing.JButton paramOKbutton;
    // End of variables declaration//GEN-END:variables
    private VAveLib_GUI mainWindow;
}
